name: sypshyt
description: A raw expense tracking app with underground vibes. Spend Your Pay, Stuff Happens You Track.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # Core Dependencies
  cupertino_icons: ^1.0.8
  
  # Data Persistence
  shared_preferences: ^2.3.2
  
  # Internationalization & Formatting
  intl: ^0.19.0
  
  # Visual Effects (iOS Compatible)
  mesh_gradient: ^1.0.0
  
  # Audio (iOS Compatible)
  audioplayers: ^5.2.1
  
  # UI Enhancements
  flutter_animate: ^4.5.0
  
  # Firebase Dependencies
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/sounds/
    - assets/icons/
    - assets/fonts/
  
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.otf
        - asset: assets/fonts/SF-Pro-Display-BlackItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
        - asset: assets/fonts/SF-Pro-Display-HeavyItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Light.otf
        - asset: assets/fonts/SF-Pro-Display-LightItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
        - asset: assets/fonts/SF-Pro-Display-ThinItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
        - asset: assets/fonts/SF-Pro-Display-UltralightItalic.otf
          style: italic
    
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
        - asset: assets/fonts/SF-Pro-Text-BoldItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
        - asset: assets/fonts/SF-Pro-Text-HeavyItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Light.otf
        - asset: assets/fonts/SF-Pro-Text-LightItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text-MediumItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-RegularItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
        - asset: assets/fonts/SF-Pro-Text-SemiboldItalic.otf
          style: italic
    
    - family: SFUIText
      fonts:
        - asset: assets/fonts/SFUIText-Regular.otf